### ISSUE TITLE
San d'Oria Mission 2-3 "Journey Abroad"

### ISSUE THREAD

**Issue by bigpurpleharness** [Demiurge-XI/feedback-and-info#35]
**Feedback or issue :**  

Sandy Mission 2-3 Bastok >> Windy Route spoken to every NPC, obtained the mythril sand but when I go to trade it to Savae E Paleade, it does not register. The NPC doesn't even turn. I reverified that I have spoken to every NPC and have tried to trade it to every NPC involved.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
what does `/ver` say you have in game?

**Comment by bigpurpleharness** [comment]
30200304_3

**Comment by TeoTwawki** [comment]
GM's log vanadate hellifIknow:
players MissionStatus was zero, yet they had received the pickaxes that required status of 3, and should have set the requires status of 5 enable the trade. For now I have force set the variable to 5 which allowed him to proceed, and will investigate further at another time using a new character.

**Comment by TeoTwawki** [comment]
Closed, mission was recoded in upstream
